### ISSUE TITLE
Investigate URLError

### ISSUE THREAD

**Issue by noppanit** [fusioneng/gif2html5-app#55]
Here's the error we got from Papertrail. It looks like the converted URL is not retrievable by URLOpener. We might need to keep trying the job. 

```
Aug 31 11:40:41 gif2html5 app/worker.1:  [2015-08-31 18:40:41,262: DEBUG/MainProcess] Task accepted: server.convert_video[d4ef1586-3480-4159-b81f-c311c8bde4ac] pid:8 
Aug 31 11:40:41 gif2html5 app/worker.1:  [2015-08-31 18:40:41,406: DEBUG/Worker-1] "GET /transcode?fetchUrl=https://fusiondotnet.files.wordpress.com/2015/08/that-mike.gif HTTP/1.1" 200 None 
Aug 31 11:40:42 gif2html5 app/worker.1:  [2015-08-31 18:40:41,817: DEBUG/Worker-1] Retrying: Gif:https://fusiondotnet.files.wordpress.com/2015/08/that-mike.gif and Webhook:https://fusiondotnet.wordpress.com/wp-admin/admin-post.php?action=gif2html5_convert_cb&attachment_id=191308&code=629d484701da3901ad20602a327b38be 
Aug 31 11:40:42 gif2html5 app/worker.1:  [2015-08-31 18:40:41,842: ERROR/MainProcess] Task server.convert_video[d4ef1586-3480-4159-b81f-c311c8bde4ac] raised unexpected: URLError('No such file or directory',) 
Aug 31 11:40:42 gif2html5 app/worker.1:  Traceback (most recent call last): 
Aug 31 11:40:42 gif2html5 app/worker.1:    File "/app/.heroku/python/lib/python3.4/site-packages/celery/app/trace.py", line 240, in trace_task 
Aug 31 11:40:42 gif2html5 app/worker.1:      R = retval = fun(*args, **kwargs) 
Aug 31 11:40:42 gif2html5 app/worker.1:    File "/app/gif2html5/celery.py", line 14, in __call__ 
Aug 31 11:40:42 gif2html5 app/worker.1:      return TaskBase.__call__(self, *args, **kwargs) 
Aug 31 11:40:42 gif2html5 app/worker.1:    File "/app/.heroku/python/lib/python3.4/site-packages/celery/app/trace.py", line 438, in __protected_call__ 
Aug 31 11:40:42 gif2html5 app/worker.1:      return self.run(*args, **kwargs) 
Aug 31 11:40:42 gif2html5 app/worker.1:    File "/app/server.py", line 54, in convert_video 
Aug 31 11:40:42 gif2html5 app/worker.1:      convert_video.retry(exc=exc) 
Aug 31 11:40:42 gif2html5 app/worker.1:    File "/app/.heroku/python/lib/python3.4/site-packages/celery/app/task.py", line 660, in retry 
Aug 31 11:40:42 gif2html5 app/worker.1:      maybe_reraise() 
Aug 31 11:40:42 gif2html5 app/worker.1:    File "/app/.heroku/python/lib/python3.4/site-packages/celery/utils/__init__.py", line 242, in maybe_reraise 
Aug 31 11:40:42 gif2html5 app/worker.1:      reraise(exc_info[0], exc_info[1], exc_info[2]) 
Aug 31 11:40:42 gif2html5 app/worker.1:    File "/app/.heroku/python/lib/python3.4/site-packages/celery/five.py", line 87, in reraise 
Aug 31 11:40:42 gif2html5 app/worker.1:      raise value 
Aug 31 11:40:42 gif2html5 app/worker.1:    File "/app/server.py", line 45, in convert_video 
Aug 31 11:40:42 gif2html5 app/worker.1:      result = convert_gif(gif_url) 
Aug 31 11:40:42 gif2html5 app/worker.1:    File "/app/gif2html5/video_manager.py", line 50, in convert 
Aug 31 11:40:42 gif2html5 app/worker.1:      urlopener.retrieve(converted_gif[ext], filename) 
Aug 31 11:40:42 gif2html5 app/worker.1:    File "/app/.heroku/python/lib/python3.4/urllib/request.py", line 1660, in retrieve 
Aug 31 11:40:42 gif2html5 app/worker.1:      fp = self.open(url, data) 
Aug 31 11:40:42 gif2html5 app/worker.1:    File "/app/.heroku/python/lib/python3.4/urllib/request.py", line 1626, in open 
Aug 31 11:40:42 gif2html5 app/worker.1:      return getattr(self, name)(url) 
Aug 31 11:40:42 gif2html5 app/worker.1:    File "/app/.heroku/python/lib/python3.4/urllib/request.py", line 1845, in open_file 
Aug 31 11:40:42 gif2html5 app/worker.1:      return self.open_local_file(url) 
Aug 31 11:40:42 gif2html5 app/worker.1:    File "/app/.heroku/python/lib/python3.4/urllib/request.py", line 1856, in open_local_file 
Aug 31 11:40:42 gif2html5 app/worker.1:      raise URLError(e.strerror, e.filename) 
Aug 31 11:40:42 gif2html5 app/worker.1:  urllib.error.URLError: <urlopen error No such file or directory> 
```

**Comment by scribu** [comment]
Why are you using `URLOpener` there, instead of the `requests` lib?

**Comment by scribu** [comment]
Also, from the error message, it looks like the problem is with the filename, not with the URL.

**Comment by noppanit** [comment]
@scribu Actually I have no preference here. I use `URLOpener` here because I can do it in a oneliner whereas `requests` I would need to open a stream and save. 

What do you think is the best way?

**Comment by scribu** [comment]
Ah, I see.

The question is: are those few extra lines saved worth the time it takes a dev not familiar with URLOpener to read its documentation? Particularly when there's an error.

**Comment by noppanit** [comment]
What do you think @mpatek for using `requests` instead of `URLOpener`. I'll be opening a new ticket if we all agree to use `requests` library. 

Closing as #56 is merged.

**Comment by mpatek** [comment]
fwiw I think `requests` is great, and think we should use it for all projects where applicable.
